import { useEffect } from 'react';
import { collection, query, where, getDocs, addDoc, updateDoc, doc, Timestamp } from 'firebase/firestore';
import { db } from '../services/firebase';
import { useFamily } from '../contexts/FamilyContext';
import { RecurringIncome } from '../types';

export const useRecurringIncomesProcessor = () => {
  const { family } = useFamily();

  useEffect(() => {
    if (!family) return;

    const processRecurringIncomes = async () => {
      try {
        const now = new Date();
        const currentMonth = now.toISOString().slice(0, 7); // "YYYY-MM"
        const currentDay = now.getDate();
        const currentMonthNum = now.getMonth() + 1; // 1-12
        const currentYear = now.getFullYear();

        // Buscar rendimentos recorrentes ativos
        const q = query(
          collection(db, 'recurringIncomes'),
          where('familyId', '==', family.id),
          where('active', '==', true)
        );

        const snapshot = await getDocs(q);
        const recurringIncomes = snapshot.docs.map(doc => ({
          id: doc.id,
          ...doc.data()
        })) as RecurringIncome[];

        for (const recurring of recurringIncomes) {
          // Se for MENSAL
          if (recurring.frequencia === 'mensal') {
            // Verifica se já foi processado neste mês
            if (recurring.lastProcessedMonth === currentMonth) {
              continue;
            }

            // Verifica se já passou o dia do mês
            if (currentDay >= recurring.diaDoMes) {
              // Calcula a data correta (dia específico do mês atual)
              const targetDate = new Date();
              targetDate.setDate(recurring.diaDoMes);
              targetDate.setHours(12, 0, 0, 0); // Meio-dia para evitar problemas de timezone

              // Cria o rendimento automático
              await addDoc(collection(db, 'incomes'), {
                familyId: family.id,
                nome: `${recurring.nome} (Automático)`,
                valor: recurring.valor,
                data: Timestamp.fromDate(targetDate),
                addedBy: recurring.createdBy,
                createdAt: Timestamp.now(),
                isAutoGenerated: true // Flag para identificar rendimentos automáticos
              });

              // Atualiza o último mês processado
              await updateDoc(doc(db, 'recurringIncomes', recurring.id), {
                lastProcessedMonth: currentMonth
              });

              console.log(`Rendimento mensal processado: ${recurring.nome}`);
            }
          }
          // Se for ANUAL
          else if (recurring.frequencia === 'anual') {
            // Verifica se já foi processado neste ano
            if (recurring.lastProcessedYear === currentYear) {
              continue;
            }

            // Verifica se já chegou o mês e o dia
            if (
              currentMonthNum > (recurring.mesDoAno || 1) ||
              (currentMonthNum === (recurring.mesDoAno || 1) && currentDay >= recurring.diaDoMes)
            ) {
              // Calcula a data correta (dia e mês específicos do ano atual)
              const targetDate = new Date(currentYear, (recurring.mesDoAno || 1) - 1, recurring.diaDoMes, 12, 0, 0, 0);

              // Cria o rendimento automático
              await addDoc(collection(db, 'incomes'), {
                familyId: family.id,
                nome: `${recurring.nome} (Automático)`,
                valor: recurring.valor,
                data: Timestamp.fromDate(targetDate),
                addedBy: recurring.createdBy,
                createdAt: Timestamp.now(),
                isAutoGenerated: true // Flag para identificar rendimentos automáticos
              });

              // Atualiza o último ano processado
              await updateDoc(doc(db, 'recurringIncomes', recurring.id), {
                lastProcessedYear: currentYear
              });

              console.log(`Rendimento anual processado: ${recurring.nome}`);
            }
          }
        }
      } catch (error) {
        console.error('Erro ao processar rendimentos recorrentes:', error);
      }
    };

    // Executa ao carregar e a cada 1 hora
    processRecurringIncomes();
    const interval = setInterval(processRecurringIncomes, 60 * 60 * 1000);

    return () => clearInterval(interval);
  }, [family]);
};

