import React, { useState } from 'react';
import { doc, updateDoc, addDoc, collection, Timestamp, query, where, getDocs } from 'firebase/firestore';
import { db } from '../services/firebase';
import { Income } from '../types';
import { useFamily } from '../contexts/FamilyContext';
import { useAuth } from '../contexts/AuthContext';
import toast from 'react-hot-toast';
import { X } from 'lucide-react';
import { format } from 'date-fns';

interface IncomeEditModalProps {
  income: Income;
  onClose: () => void;
  onSuccess: () => void;
}

const IncomeEditModal: React.FC<IncomeEditModalProps> = ({ income, onClose, onSuccess }) => {
  const { family } = useFamily();
  const { currentUser } = useAuth();
  const [nome, setNome] = useState(income.nome);
  const [valor, setValor] = useState(income.valor.toString());
  const [data, setData] = useState(format(income.data, 'yyyy-MM-dd'));
  const [isRecurring, setIsRecurring] = useState(false);
  const [frequencia, setFrequencia] = useState<'mensal' | 'anual'>('mensal');
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!nome || !valor) {
      toast.error('Preencha todos os campos');
      return;
    }

    const valorNumerico = parseFloat(valor);
    if (isNaN(valorNumerico) || valorNumerico <= 0) {
      toast.error('Digite um valor válido');
      return;
    }

    setLoading(true);
    try {
      await updateDoc(doc(db, 'incomes', income.id), {
        nome: nome,
        valor: valorNumerico,
        data: new Date(data)
      });

      // Se marcou como rendimento fixo, cria o rendimento recorrente
      if (isRecurring && family && currentUser) {
        const selectedDate = new Date(data);
        const diaDoMes = selectedDate.getDate();
        const mesDoAno = selectedDate.getMonth() + 1;
        const currentMonth = new Date().toISOString().slice(0, 7);
        const currentYear = new Date().getFullYear();
        
        // Verificar se já existe um rendimento recorrente idêntico
        const checkQuery = query(
          collection(db, 'recurringIncomes'),
          where('familyId', '==', family.id),
          where('nome', '==', nome),
          where('diaDoMes', '==', diaDoMes),
          where('frequencia', '==', frequencia),
          where('active', '==', true)
        );
        
        const existingDocs = await getDocs(checkQuery);
        
        // Se for anual, também verificar o mês
        const hasDuplicate = existingDocs.docs.some(doc => {
          const data = doc.data();
          if (frequencia === 'anual') {
            return data.mesDoAno === mesDoAno;
          }
          return true; // Para mensal, apenas nome + dia já é suficiente
        });
        
        if (hasDuplicate) {
          toast.error('Já existe um rendimento fixo idêntico cadastrado!');
          setLoading(false);
          return;
        }
        
        const recurringData: any = {
          familyId: family.id,
          nome: nome,
          valor: valorNumerico,
          diaDoMes: diaDoMes,
          mesDoAno: mesDoAno,
          frequencia: frequencia,
          createdBy: currentUser.uid,
          createdAt: Timestamp.now(),
          active: true,
          lastProcessedMonth: currentMonth
        };
        
        // Só adiciona lastProcessedYear se for anual
        if (frequencia === 'anual') {
          recurringData.lastProcessedYear = currentYear;
        }
        
        await addDoc(collection(db, 'recurringIncomes'), recurringData);

        // Se for anual, cria os rendimentos dos próximos 5 anos
        if (frequencia === 'anual') {
          for (let year = 1; year <= 5; year++) {
            const futureDate = new Date(selectedDate);
            futureDate.setFullYear(selectedDate.getFullYear() + year);
            
            await addDoc(collection(db, 'incomes'), {
              familyId: family.id,
              nome: `${nome} (Automático)`,
              valor: valorNumerico,
              data: Timestamp.fromDate(futureDate),
              addedBy: currentUser.uid,
              createdAt: Timestamp.now(),
              isAutoGenerated: true
            });
          }
        }
      }

      toast.success(isRecurring ? `Rendimento atualizado e marcado como fixo ${frequencia}!` : 'Rendimento atualizado!');
      onSuccess();
      onClose();
    } catch (error) {
      console.error(error);
      toast.error('Erro ao atualizar rendimento');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
      <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-2xl p-6 w-full max-w-md">
        <div className="flex items-center justify-between mb-4">
          <h3 className="text-xl font-semibold text-gray-800 dark:text-white">
            Editar Rendimento
          </h3>
          <button
            onClick={onClose}
            className="text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-white transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="space-y-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
              Nome do Rendimento
            </label>
            <input
              type="text"
              value={nome}
              onChange={(e) => setNome(e.target.value)}
              className="w-full px-4 py-2.5 border-2 border-gray-200 dark:border-gray-600 rounded-xl focus:ring-2 focus:ring-green-500 focus:border-green-500 transition-all outline-none bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
            />
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                Valor
              </label>
              <input
                type="number"
                step="0.01"
                value={valor}
                onChange={(e) => setValor(e.target.value)}
                className="w-full px-4 py-2.5 border-2 border-gray-200 dark:border-gray-600 rounded-xl focus:ring-2 focus:ring-green-500 focus:border-green-500 transition-all outline-none bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                Data
              </label>
              <input
                type="date"
                value={data}
                onChange={(e) => setData(e.target.value)}
                className="w-full px-4 py-2.5 border-2 border-gray-200 dark:border-gray-600 rounded-xl focus:ring-2 focus:ring-green-500 focus:border-green-500 transition-all outline-none bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
              />
            </div>
          </div>

          <div className="p-4 bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-xl space-y-3">
            <div className="flex items-center gap-3">
              <input
                type="checkbox"
                id="isRecurringEdit"
                checked={isRecurring}
                onChange={(e) => setIsRecurring(e.target.checked)}
                className="w-4 h-4 text-green-600 border-gray-300 rounded focus:ring-green-500"
              />
              <label htmlFor="isRecurringEdit" className="text-sm font-medium text-gray-700 dark:text-gray-300 cursor-pointer">
                Marcar como <strong>Rendimento Fixo</strong>
              </label>
            </div>

            {isRecurring && (
              <div className="space-y-3 ml-7">
                <div className="flex items-center gap-4">
                  <label className="flex items-center gap-2 cursor-pointer">
                    <input
                      type="radio"
                      name="frequencia"
                      value="mensal"
                      checked={frequencia === 'mensal'}
                      onChange={(e) => setFrequencia(e.target.value as 'mensal')}
                      className="w-4 h-4 text-green-600 border-gray-300 focus:ring-green-500"
                    />
                    <span className="text-sm text-gray-700 dark:text-gray-300">
                      Mensal (todo dia {new Date(data).getDate()})
                    </span>
                  </label>

                  <label className="flex items-center gap-2 cursor-pointer">
                    <input
                      type="radio"
                      name="frequencia"
                      value="anual"
                      checked={frequencia === 'anual'}
                      onChange={(e) => setFrequencia(e.target.value as 'anual')}
                      className="w-4 h-4 text-green-600 border-gray-300 focus:ring-green-500"
                    />
                    <span className="text-sm text-gray-700 dark:text-gray-300">
                      Anual (dia {new Date(data).getDate()}/{new Date(data).getMonth() + 1} de cada ano)
                    </span>
                  </label>
                </div>

                {frequencia === 'anual' && (
                  <p className="text-xs text-gray-600 dark:text-gray-400">
                    Serão criados rendimentos automáticos para os próximos 5 anos
                  </p>
                )}
              </div>
            )}
          </div>

          <div className="flex gap-2 pt-2">
            <button
              type="submit"
              disabled={loading}
              className="flex-1 bg-green-600 text-white py-3 rounded-xl font-semibold hover:bg-green-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {loading ? 'Salvando...' : 'Salvar Alterações'}
            </button>
            <button
              type="button"
              onClick={onClose}
              className="px-6 py-3 border-2 border-gray-300 dark:border-gray-600 text-gray-700 dark:text-gray-300 rounded-xl font-medium hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors"
            >
              Cancelar
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default IncomeEditModal;

